### ISSUE TITLE
I don't file pickel_model.pkl !!!!

### ISSUE THREAD

**Issue by KIKIPEN** [VAD3R-95/Malicious-Url-Detection#2]
![image](https://user-images.githubusercontent.com/56993387/77386555-a99b5f80-6dbd-11ea-9c40-118479097ba7.png)

**Comment by VAD3R-95** [comment]
Sorry for late reply !
Well you have to train your model using the malicious_url.py which will save and generate those models in python pickel files which can be run using the whitelist_url.py for future n no. of times without having to generate the model again. You can follow a full step-by-step process here : [VAD3R_BLOGS](https://vad3rblog.wordpress.com/2018/04/08/malicious-url-detection/). If you still have any doubts let me know.

**Comment by VAD3R-95** [comment]
If you want to use my test pickel dumps then you can unzip them and save them in the folder where you have whitelist_url.py script and then change your test webistes inside the script. I will update whitelist_url.py to take input from terminal in some time.
